/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ColorPalette {
  'accent' : string,
  'background' : string,
  'text' : string,
  'secondary' : string,
  'primary' : string,
}
export interface GeneratedSite {
  'siteTitle' : string,
  'tagline' : string,
  'layout' : LayoutMetadata,
  'colorPalette' : ColorPalette,
  'sections' : Array<SiteSection>,
}
export interface LayoutMetadata {
  'borderRadius' : string,
  'layoutStyle' : string,
  'fontFamily' : string,
}
export interface PreLaunchChecks {
  'seo' : boolean,
  'formsValid' : boolean,
  'performanceHint' : boolean,
  'mobileReady' : boolean,
}
export type PublishStatus = { 'published' : null } |
  { 'publishing' : null } |
  { 'unpublished' : null } |
  { 'failed' : null };
export type SectionType = { 'contact' : null } |
  { 'about' : null } |
  { 'hero' : null } |
  { 'services' : null } |
  { 'footer' : null };
export interface SelectedFeatures {
  'contactForm' : boolean,
  'bookings' : boolean,
  'auth' : boolean,
}
export type SiteId = bigint;
export interface SitePublic {
  'id' : SiteId,
  'status' : PublishStatus,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'publishedUrl' : [] | [string],
  'updatedAt' : Timestamp,
  'generatedData' : [] | [GeneratedSite],
  'subdomain' : [] | [string],
}
export interface SiteSection {
  'subheading' : string,
  'content' : string,
  'sectionType' : SectionType,
  'heading' : string,
}
export interface SiteSummary {
  'id' : SiteId,
  'status' : PublishStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'subdomain' : [] | [string],
}
export type SiteType = { 'portfolio' : null } |
  { 'blog' : null } |
  { 'business' : null } |
  { 'landing' : null } |
  { 'ecommerce' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisualStyle {
  'primaryColor' : string,
  'fontFamily' : string,
  'secondaryColor' : string,
}
export interface WizardInput {
  'visualStyle' : VisualStyle,
  'siteType' : SiteType,
  'businessDescription' : string,
  'selectedFeatures' : SelectedFeatures,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSite' : ActorMethod<[SiteId], undefined>,
  'generateSite' : ActorMethod<[WizardInput], SitePublic>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreLaunchChecks' : ActorMethod<[SiteId], PreLaunchChecks>,
  'getSite' : ActorMethod<[SiteId], [] | [SitePublic]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMySites' : ActorMethod<[], Array<SiteSummary>>,
  'publishSite' : ActorMethod<[SiteId], SitePublic>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSite' : ActorMethod<
    [SiteId, [] | [string], [] | [GeneratedSite]],
    SitePublic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];