/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SiteId = IDL.Nat;
export const SelectedFeature = IDL.Variant({
  'contactForm' : IDL.Null,
  'userAccounts' : IDL.Null,
  'payments' : IDL.Null,
  'blog' : IDL.Null,
  'liveChat' : IDL.Null,
  'newsletter' : IDL.Null,
  'testimonials' : IDL.Null,
  'bookingCalendar' : IDL.Null,
  'imageGallery' : IDL.Null,
});
export const VisualStyle = IDL.Variant({
  'bold' : IDL.Null,
  'minimal' : IDL.Null,
  'warm' : IDL.Null,
  'playful' : IDL.Null,
  'luxury' : IDL.Null,
});
export const SiteType = IDL.Variant({
  'portfolio' : IDL.Null,
  'blog' : IDL.Null,
  'saas' : IDL.Null,
  'agency' : IDL.Null,
  'booking' : IDL.Null,
  'landingPage' : IDL.Null,
  'restaurant' : IDL.Null,
  'ecommerce' : IDL.Null,
});
export const WizardInput = IDL.Record({
  'features' : IDL.Vec(SelectedFeature),
  'vibe' : VisualStyle,
  'siteType' : SiteType,
  'niche' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'plan' : IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null }),
  'email' : IDL.Text,
});
export const PreLaunchChecks = IDL.Record({
  'seo' : IDL.Bool,
  'forms' : IDL.Bool,
  'seoNote' : IDL.Text,
  'speedNote' : IDL.Text,
  'formsNote' : IDL.Text,
  'speed' : IDL.Nat,
  'mobile' : IDL.Bool,
  'mobileNote' : IDL.Text,
});
export const PublishStatus = IDL.Variant({
  'live' : IDL.Null,
  'draft' : IDL.Null,
});
export const UserId = IDL.Principal;
export const SitePublic = IDL.Record({
  'id' : SiteId,
  'status' : PublishStatus,
  'features' : IDL.Vec(SelectedFeature),
  'formSubmissions' : IDL.Nat,
  'visitors' : IDL.Nat,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'slug' : IDL.Text,
  'vibe' : VisualStyle,
  'publishedAt' : IDL.Opt(Timestamp),
  'siteType' : SiteType,
  'updatedAt' : Timestamp,
  'niche' : IDL.Text,
  'lighthouseScore' : IDL.Nat,
  'siteUrl' : IDL.Opt(IDL.Text),
});
export const SiteSummary = IDL.Record({
  'id' : SiteId,
  'status' : PublishStatus,
  'formSubmissions' : IDL.Nat,
  'visitors' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'updatedAt' : Timestamp,
  'lighthouseScore' : IDL.Nat,
  'siteUrl' : IDL.Opt(IDL.Text),
});
export const SiteUpdate = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'niche' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSite' : IDL.Func([SiteId], [IDL.Bool], []),
  'generateSite' : IDL.Func([WizardInput], [SiteId, IDL.Text], []),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPreLaunchChecks' : IDL.Func(
      [SiteId],
      [IDL.Opt(PreLaunchChecks)],
      ['query'],
    ),
  'getSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMySites' : IDL.Func([], [IDL.Vec(SiteSummary)], ['query']),
  'publishSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], []),
  'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'updateSite' : IDL.Func([SiteId, SiteUpdate], [IDL.Opt(SitePublic)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SiteId = IDL.Nat;
  const SelectedFeature = IDL.Variant({
    'contactForm' : IDL.Null,
    'userAccounts' : IDL.Null,
    'payments' : IDL.Null,
    'blog' : IDL.Null,
    'liveChat' : IDL.Null,
    'newsletter' : IDL.Null,
    'testimonials' : IDL.Null,
    'bookingCalendar' : IDL.Null,
    'imageGallery' : IDL.Null,
  });
  const VisualStyle = IDL.Variant({
    'bold' : IDL.Null,
    'minimal' : IDL.Null,
    'warm' : IDL.Null,
    'playful' : IDL.Null,
    'luxury' : IDL.Null,
  });
  const SiteType = IDL.Variant({
    'portfolio' : IDL.Null,
    'blog' : IDL.Null,
    'saas' : IDL.Null,
    'agency' : IDL.Null,
    'booking' : IDL.Null,
    'landingPage' : IDL.Null,
    'restaurant' : IDL.Null,
    'ecommerce' : IDL.Null,
  });
  const WizardInput = IDL.Record({
    'features' : IDL.Vec(SelectedFeature),
    'vibe' : VisualStyle,
    'siteType' : SiteType,
    'niche' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'plan' : IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null }),
    'email' : IDL.Text,
  });
  const PreLaunchChecks = IDL.Record({
    'seo' : IDL.Bool,
    'forms' : IDL.Bool,
    'seoNote' : IDL.Text,
    'speedNote' : IDL.Text,
    'formsNote' : IDL.Text,
    'speed' : IDL.Nat,
    'mobile' : IDL.Bool,
    'mobileNote' : IDL.Text,
  });
  const PublishStatus = IDL.Variant({ 'live' : IDL.Null, 'draft' : IDL.Null });
  const UserId = IDL.Principal;
  const SitePublic = IDL.Record({
    'id' : SiteId,
    'status' : PublishStatus,
    'features' : IDL.Vec(SelectedFeature),
    'formSubmissions' : IDL.Nat,
    'visitors' : IDL.Nat,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'slug' : IDL.Text,
    'vibe' : VisualStyle,
    'publishedAt' : IDL.Opt(Timestamp),
    'siteType' : SiteType,
    'updatedAt' : Timestamp,
    'niche' : IDL.Text,
    'lighthouseScore' : IDL.Nat,
    'siteUrl' : IDL.Opt(IDL.Text),
  });
  const SiteSummary = IDL.Record({
    'id' : SiteId,
    'status' : PublishStatus,
    'formSubmissions' : IDL.Nat,
    'visitors' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'updatedAt' : Timestamp,
    'lighthouseScore' : IDL.Nat,
    'siteUrl' : IDL.Opt(IDL.Text),
  });
  const SiteUpdate = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'niche' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSite' : IDL.Func([SiteId], [IDL.Bool], []),
    'generateSite' : IDL.Func([WizardInput], [SiteId, IDL.Text], []),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPreLaunchChecks' : IDL.Func(
        [SiteId],
        [IDL.Opt(PreLaunchChecks)],
        ['query'],
      ),
    'getSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMySites' : IDL.Func([], [IDL.Vec(SiteSummary)], ['query']),
    'publishSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], []),
    'saveCallerProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'updateSite' : IDL.Func([SiteId, SiteUpdate], [IDL.Opt(SitePublic)], []),
  });
};

export const init = ({ IDL }) => { return []; };