/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PreLaunchChecks {
  'seo' : boolean,
  'forms' : boolean,
  'seoNote' : string,
  'speedNote' : string,
  'formsNote' : string,
  'speed' : bigint,
  'mobile' : boolean,
  'mobileNote' : string,
}
export type PublishStatus = { 'live' : null } |
  { 'draft' : null };
export type SelectedFeature = { 'contactForm' : null } |
  { 'userAccounts' : null } |
  { 'payments' : null } |
  { 'blog' : null } |
  { 'liveChat' : null } |
  { 'newsletter' : null } |
  { 'testimonials' : null } |
  { 'bookingCalendar' : null } |
  { 'imageGallery' : null };
export type SiteId = bigint;
export interface SitePublic {
  'id' : SiteId,
  'status' : PublishStatus,
  'features' : Array<SelectedFeature>,
  'formSubmissions' : bigint,
  'visitors' : bigint,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'slug' : string,
  'vibe' : VisualStyle,
  'publishedAt' : [] | [Timestamp],
  'siteType' : SiteType,
  'updatedAt' : Timestamp,
  'niche' : string,
  'lighthouseScore' : bigint,
  'siteUrl' : [] | [string],
}
export interface SiteSummary {
  'id' : SiteId,
  'status' : PublishStatus,
  'formSubmissions' : bigint,
  'visitors' : bigint,
  'name' : string,
  'slug' : string,
  'updatedAt' : Timestamp,
  'lighthouseScore' : bigint,
  'siteUrl' : [] | [string],
}
export type SiteType = { 'portfolio' : null } |
  { 'blog' : null } |
  { 'saas' : null } |
  { 'agency' : null } |
  { 'booking' : null } |
  { 'landingPage' : null } |
  { 'restaurant' : null } |
  { 'ecommerce' : null };
export interface SiteUpdate { 'name' : [] | [string], 'niche' : [] | [string] }
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'plan' : { 'pro' : null } |
    { 'free' : null },
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VisualStyle = { 'bold' : null } |
  { 'minimal' : null } |
  { 'warm' : null } |
  { 'playful' : null } |
  { 'luxury' : null };
export interface WizardInput {
  'features' : Array<SelectedFeature>,
  'vibe' : VisualStyle,
  'siteType' : SiteType,
  'niche' : string,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSite' : ActorMethod<[SiteId], boolean>,
  'generateSite' : ActorMethod<[WizardInput], [SiteId, string]>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreLaunchChecks' : ActorMethod<[SiteId], [] | [PreLaunchChecks]>,
  'getSite' : ActorMethod<[SiteId], [] | [SitePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMySites' : ActorMethod<[], Array<SiteSummary>>,
  'publishSite' : ActorMethod<[SiteId], [] | [SitePublic]>,
  'saveCallerProfile' : ActorMethod<[string, string], UserProfile>,
  'updateSite' : ActorMethod<[SiteId, SiteUpdate], [] | [SitePublic]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];