/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SiteId = IDL.Nat;
export const VisualStyle = IDL.Record({
  'primaryColor' : IDL.Text,
  'fontFamily' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const SiteType = IDL.Variant({
  'portfolio' : IDL.Null,
  'blog' : IDL.Null,
  'business' : IDL.Null,
  'landing' : IDL.Null,
  'ecommerce' : IDL.Null,
});
export const SelectedFeatures = IDL.Record({
  'contactForm' : IDL.Bool,
  'bookings' : IDL.Bool,
  'auth' : IDL.Bool,
});
export const WizardInput = IDL.Record({
  'visualStyle' : VisualStyle,
  'siteType' : SiteType,
  'businessDescription' : IDL.Text,
  'selectedFeatures' : SelectedFeatures,
});
export const PublishStatus = IDL.Variant({
  'published' : IDL.Null,
  'publishing' : IDL.Null,
  'unpublished' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const LayoutMetadata = IDL.Record({
  'borderRadius' : IDL.Text,
  'layoutStyle' : IDL.Text,
  'fontFamily' : IDL.Text,
});
export const ColorPalette = IDL.Record({
  'accent' : IDL.Text,
  'background' : IDL.Text,
  'text' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const SectionType = IDL.Variant({
  'contact' : IDL.Null,
  'about' : IDL.Null,
  'hero' : IDL.Null,
  'services' : IDL.Null,
  'footer' : IDL.Null,
});
export const SiteSection = IDL.Record({
  'subheading' : IDL.Text,
  'content' : IDL.Text,
  'sectionType' : SectionType,
  'heading' : IDL.Text,
});
export const GeneratedSite = IDL.Record({
  'siteTitle' : IDL.Text,
  'tagline' : IDL.Text,
  'layout' : LayoutMetadata,
  'colorPalette' : ColorPalette,
  'sections' : IDL.Vec(SiteSection),
});
export const SitePublic = IDL.Record({
  'id' : SiteId,
  'status' : PublishStatus,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'publishedUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'generatedData' : IDL.Opt(GeneratedSite),
  'subdomain' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const PreLaunchChecks = IDL.Record({
  'seo' : IDL.Bool,
  'formsValid' : IDL.Bool,
  'performanceHint' : IDL.Bool,
  'mobileReady' : IDL.Bool,
});
export const SiteSummary = IDL.Record({
  'id' : SiteId,
  'status' : PublishStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'subdomain' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSite' : IDL.Func([SiteId], [], []),
  'generateSite' : IDL.Func([WizardInput], [SitePublic], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPreLaunchChecks' : IDL.Func([SiteId], [PreLaunchChecks], ['query']),
  'getSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMySites' : IDL.Func([], [IDL.Vec(SiteSummary)], ['query']),
  'publishSite' : IDL.Func([SiteId], [SitePublic], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSite' : IDL.Func(
      [SiteId, IDL.Opt(IDL.Text), IDL.Opt(GeneratedSite)],
      [SitePublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SiteId = IDL.Nat;
  const VisualStyle = IDL.Record({
    'primaryColor' : IDL.Text,
    'fontFamily' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const SiteType = IDL.Variant({
    'portfolio' : IDL.Null,
    'blog' : IDL.Null,
    'business' : IDL.Null,
    'landing' : IDL.Null,
    'ecommerce' : IDL.Null,
  });
  const SelectedFeatures = IDL.Record({
    'contactForm' : IDL.Bool,
    'bookings' : IDL.Bool,
    'auth' : IDL.Bool,
  });
  const WizardInput = IDL.Record({
    'visualStyle' : VisualStyle,
    'siteType' : SiteType,
    'businessDescription' : IDL.Text,
    'selectedFeatures' : SelectedFeatures,
  });
  const PublishStatus = IDL.Variant({
    'published' : IDL.Null,
    'publishing' : IDL.Null,
    'unpublished' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const LayoutMetadata = IDL.Record({
    'borderRadius' : IDL.Text,
    'layoutStyle' : IDL.Text,
    'fontFamily' : IDL.Text,
  });
  const ColorPalette = IDL.Record({
    'accent' : IDL.Text,
    'background' : IDL.Text,
    'text' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const SectionType = IDL.Variant({
    'contact' : IDL.Null,
    'about' : IDL.Null,
    'hero' : IDL.Null,
    'services' : IDL.Null,
    'footer' : IDL.Null,
  });
  const SiteSection = IDL.Record({
    'subheading' : IDL.Text,
    'content' : IDL.Text,
    'sectionType' : SectionType,
    'heading' : IDL.Text,
  });
  const GeneratedSite = IDL.Record({
    'siteTitle' : IDL.Text,
    'tagline' : IDL.Text,
    'layout' : LayoutMetadata,
    'colorPalette' : ColorPalette,
    'sections' : IDL.Vec(SiteSection),
  });
  const SitePublic = IDL.Record({
    'id' : SiteId,
    'status' : PublishStatus,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'publishedUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'generatedData' : IDL.Opt(GeneratedSite),
    'subdomain' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const PreLaunchChecks = IDL.Record({
    'seo' : IDL.Bool,
    'formsValid' : IDL.Bool,
    'performanceHint' : IDL.Bool,
    'mobileReady' : IDL.Bool,
  });
  const SiteSummary = IDL.Record({
    'id' : SiteId,
    'status' : PublishStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'subdomain' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSite' : IDL.Func([SiteId], [], []),
    'generateSite' : IDL.Func([WizardInput], [SitePublic], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPreLaunchChecks' : IDL.Func([SiteId], [PreLaunchChecks], ['query']),
    'getSite' : IDL.Func([SiteId], [IDL.Opt(SitePublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMySites' : IDL.Func([], [IDL.Vec(SiteSummary)], ['query']),
    'publishSite' : IDL.Func([SiteId], [SitePublic], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSite' : IDL.Func(
        [SiteId, IDL.Opt(IDL.Text), IDL.Opt(GeneratedSite)],
        [SitePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };