/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WizardInput {
    features: Array<SelectedFeature>;
    vibe: VisualStyle;
    siteType: SiteType;
    niche: string;
}
export type Timestamp = bigint;
export interface SiteSummary {
    id: SiteId;
    status: PublishStatus;
    formSubmissions: bigint;
    visitors: bigint;
    name: string;
    slug: string;
    updatedAt: Timestamp;
    lighthouseScore: bigint;
    siteUrl?: string;
}
export interface SiteUpdate {
    name?: string;
    niche?: string;
}
export type SiteId = bigint;
export type UserId = Principal;
export interface SitePublic {
    id: SiteId;
    status: PublishStatus;
    features: Array<SelectedFeature>;
    formSubmissions: bigint;
    visitors: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    slug: string;
    vibe: VisualStyle;
    publishedAt?: Timestamp;
    siteType: SiteType;
    updatedAt: Timestamp;
    niche: string;
    lighthouseScore: bigint;
    siteUrl?: string;
}
export interface PreLaunchChecks {
    seo: boolean;
    forms: boolean;
    seoNote: string;
    speedNote: string;
    formsNote: string;
    speed: bigint;
    mobile: boolean;
    mobileNote: string;
}
export interface UserProfile {
    name: string;
    createdAt: Timestamp;
    plan: Variant_pro_free;
    email: string;
}
export enum PublishStatus {
    live = "live",
    draft = "draft"
}
export enum SelectedFeature {
    contactForm = "contactForm",
    userAccounts = "userAccounts",
    payments = "payments",
    blog = "blog",
    liveChat = "liveChat",
    newsletter = "newsletter",
    testimonials = "testimonials",
    bookingCalendar = "bookingCalendar",
    imageGallery = "imageGallery"
}
export enum SiteType {
    portfolio = "portfolio",
    blog = "blog",
    saas = "saas",
    agency = "agency",
    booking = "booking",
    landingPage = "landingPage",
    restaurant = "restaurant",
    ecommerce = "ecommerce"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pro_free {
    pro = "pro",
    free = "free"
}
export enum VisualStyle {
    bold = "bold",
    minimal = "minimal",
    warm = "warm",
    playful = "playful",
    luxury = "luxury"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteSite(id: SiteId): Promise<boolean>;
    generateSite(input: WizardInput): Promise<[SiteId, string]>;
    getCallerProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPreLaunchChecks(id: SiteId): Promise<PreLaunchChecks | null>;
    getSite(id: SiteId): Promise<SitePublic | null>;
    isCallerAdmin(): Promise<boolean>;
    listMySites(): Promise<Array<SiteSummary>>;
    publishSite(id: SiteId): Promise<SitePublic | null>;
    saveCallerProfile(name: string, email: string): Promise<UserProfile>;
    updateSite(id: SiteId, updates: SiteUpdate): Promise<SitePublic | null>;
}
import type { PreLaunchChecks as _PreLaunchChecks, PublishStatus as _PublishStatus, SelectedFeature as _SelectedFeature, SiteId as _SiteId, SitePublic as _SitePublic, SiteSummary as _SiteSummary, SiteType as _SiteType, SiteUpdate as _SiteUpdate, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, VisualStyle as _VisualStyle, WizardInput as _WizardInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteSite(arg0: SiteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async generateSite(arg0: WizardInput): Promise<[SiteId, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSite(to_candid_WizardInput_n3(this._uploadFile, this._downloadFile, arg0));
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSite(to_candid_WizardInput_n3(this._uploadFile, this._downloadFile, arg0));
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getCallerProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreLaunchChecks(arg0: SiteId): Promise<PreLaunchChecks | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreLaunchChecks(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreLaunchChecks(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSite(arg0: SiteId): Promise<SitePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSite(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSite(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMySites(): Promise<Array<SiteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMySites();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMySites();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishSite(arg0: SiteId): Promise<SitePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.publishSite(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishSite(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerProfile(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerProfile(arg0, arg1);
                return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerProfile(arg0, arg1);
            return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSite(arg0: SiteId, arg1: SiteUpdate): Promise<SitePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, to_candid_SiteUpdate_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, to_candid_SiteUpdate_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PublishStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishStatus): PublishStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SelectedFeature_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SelectedFeature): SelectedFeature {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SitePublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SitePublic): SitePublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SiteSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSummary): SiteSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_SiteType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteType): SiteType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_VisualStyle_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisualStyle): VisualStyle {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PreLaunchChecks]): PreLaunchChecks | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SitePublic]): SitePublic | null {
    return value.length === 0 ? null : from_candid_SitePublic_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Timestamp;
    plan: {
        pro: null;
    } | {
        free: null;
    };
    email: string;
}): {
    name: string;
    createdAt: Timestamp;
    plan: Variant_pro_free;
    email: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        plan: from_candid_variant_n15(_uploadFile, _downloadFile, value.plan),
        email: value.email
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SiteId;
    status: _PublishStatus;
    features: Array<_SelectedFeature>;
    formSubmissions: bigint;
    visitors: bigint;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    slug: string;
    vibe: _VisualStyle;
    publishedAt: [] | [_Timestamp];
    siteType: _SiteType;
    updatedAt: _Timestamp;
    niche: string;
    lighthouseScore: bigint;
    siteUrl: [] | [string];
}): {
    id: SiteId;
    status: PublishStatus;
    features: Array<SelectedFeature>;
    formSubmissions: bigint;
    visitors: bigint;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    slug: string;
    vibe: VisualStyle;
    publishedAt?: Timestamp;
    siteType: SiteType;
    updatedAt: Timestamp;
    niche: string;
    lighthouseScore: bigint;
    siteUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_PublishStatus_n22(_uploadFile, _downloadFile, value.status),
        features: from_candid_vec_n24(_uploadFile, _downloadFile, value.features),
        formSubmissions: value.formSubmissions,
        visitors: value.visitors,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        slug: value.slug,
        vibe: from_candid_VisualStyle_n27(_uploadFile, _downloadFile, value.vibe),
        publishedAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.publishedAt)),
        siteType: from_candid_SiteType_n30(_uploadFile, _downloadFile, value.siteType),
        updatedAt: value.updatedAt,
        niche: value.niche,
        lighthouseScore: value.lighthouseScore,
        siteUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.siteUrl))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SiteId;
    status: _PublishStatus;
    formSubmissions: bigint;
    visitors: bigint;
    name: string;
    slug: string;
    updatedAt: _Timestamp;
    lighthouseScore: bigint;
    siteUrl: [] | [string];
}): {
    id: SiteId;
    status: PublishStatus;
    formSubmissions: bigint;
    visitors: bigint;
    name: string;
    slug: string;
    updatedAt: Timestamp;
    lighthouseScore: bigint;
    siteUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_PublishStatus_n22(_uploadFile, _downloadFile, value.status),
        formSubmissions: value.formSubmissions,
        visitors: value.visitors,
        name: value.name,
        slug: value.slug,
        updatedAt: value.updatedAt,
        lighthouseScore: value.lighthouseScore,
        siteUrl: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.siteUrl))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    free: null;
}): Variant_pro_free {
    return "pro" in value ? Variant_pro_free.pro : "free" in value ? Variant_pro_free.free : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    live: null;
} | {
    draft: null;
}): PublishStatus {
    return "live" in value ? PublishStatus.live : "draft" in value ? PublishStatus.draft : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactForm: null;
} | {
    userAccounts: null;
} | {
    payments: null;
} | {
    blog: null;
} | {
    liveChat: null;
} | {
    newsletter: null;
} | {
    testimonials: null;
} | {
    bookingCalendar: null;
} | {
    imageGallery: null;
}): SelectedFeature {
    return "contactForm" in value ? SelectedFeature.contactForm : "userAccounts" in value ? SelectedFeature.userAccounts : "payments" in value ? SelectedFeature.payments : "blog" in value ? SelectedFeature.blog : "liveChat" in value ? SelectedFeature.liveChat : "newsletter" in value ? SelectedFeature.newsletter : "testimonials" in value ? SelectedFeature.testimonials : "bookingCalendar" in value ? SelectedFeature.bookingCalendar : "imageGallery" in value ? SelectedFeature.imageGallery : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bold: null;
} | {
    minimal: null;
} | {
    warm: null;
} | {
    playful: null;
} | {
    luxury: null;
}): VisualStyle {
    return "bold" in value ? VisualStyle.bold : "minimal" in value ? VisualStyle.minimal : "warm" in value ? VisualStyle.warm : "playful" in value ? VisualStyle.playful : "luxury" in value ? VisualStyle.luxury : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    portfolio: null;
} | {
    blog: null;
} | {
    saas: null;
} | {
    agency: null;
} | {
    booking: null;
} | {
    landingPage: null;
} | {
    restaurant: null;
} | {
    ecommerce: null;
}): SiteType {
    return "portfolio" in value ? SiteType.portfolio : "blog" in value ? SiteType.blog : "saas" in value ? SiteType.saas : "agency" in value ? SiteType.agency : "booking" in value ? SiteType.booking : "landingPage" in value ? SiteType.landingPage : "restaurant" in value ? SiteType.restaurant : "ecommerce" in value ? SiteType.ecommerce : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SelectedFeature>): Array<SelectedFeature> {
    return value.map((x)=>from_candid_SelectedFeature_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SiteSummary>): Array<SiteSummary> {
    return value.map((x)=>from_candid_SiteSummary_n34(_uploadFile, _downloadFile, x));
}
function to_candid_SelectedFeature_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SelectedFeature): _SelectedFeature {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SiteType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteType): _SiteType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SiteUpdate_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteUpdate): _SiteUpdate {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VisualStyle_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualStyle): _VisualStyle {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WizardInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WizardInput): _WizardInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    niche?: string;
}): {
    name: [] | [string];
    niche: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        niche: value.niche ? candid_some(value.niche) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<SelectedFeature>;
    vibe: VisualStyle;
    siteType: SiteType;
    niche: string;
}): {
    features: Array<_SelectedFeature>;
    vibe: _VisualStyle;
    siteType: _SiteType;
    niche: string;
} {
    return {
        features: to_candid_vec_n5(_uploadFile, _downloadFile, value.features),
        vibe: to_candid_VisualStyle_n8(_uploadFile, _downloadFile, value.vibe),
        siteType: to_candid_SiteType_n10(_uploadFile, _downloadFile, value.siteType),
        niche: value.niche
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteType): {
    portfolio: null;
} | {
    blog: null;
} | {
    saas: null;
} | {
    agency: null;
} | {
    booking: null;
} | {
    landingPage: null;
} | {
    restaurant: null;
} | {
    ecommerce: null;
} {
    return value == SiteType.portfolio ? {
        portfolio: null
    } : value == SiteType.blog ? {
        blog: null
    } : value == SiteType.saas ? {
        saas: null
    } : value == SiteType.agency ? {
        agency: null
    } : value == SiteType.booking ? {
        booking: null
    } : value == SiteType.landingPage ? {
        landingPage: null
    } : value == SiteType.restaurant ? {
        restaurant: null
    } : value == SiteType.ecommerce ? {
        ecommerce: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SelectedFeature): {
    contactForm: null;
} | {
    userAccounts: null;
} | {
    payments: null;
} | {
    blog: null;
} | {
    liveChat: null;
} | {
    newsletter: null;
} | {
    testimonials: null;
} | {
    bookingCalendar: null;
} | {
    imageGallery: null;
} {
    return value == SelectedFeature.contactForm ? {
        contactForm: null
    } : value == SelectedFeature.userAccounts ? {
        userAccounts: null
    } : value == SelectedFeature.payments ? {
        payments: null
    } : value == SelectedFeature.blog ? {
        blog: null
    } : value == SelectedFeature.liveChat ? {
        liveChat: null
    } : value == SelectedFeature.newsletter ? {
        newsletter: null
    } : value == SelectedFeature.testimonials ? {
        testimonials: null
    } : value == SelectedFeature.bookingCalendar ? {
        bookingCalendar: null
    } : value == SelectedFeature.imageGallery ? {
        imageGallery: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisualStyle): {
    bold: null;
} | {
    minimal: null;
} | {
    warm: null;
} | {
    playful: null;
} | {
    luxury: null;
} {
    return value == VisualStyle.bold ? {
        bold: null
    } : value == VisualStyle.minimal ? {
        minimal: null
    } : value == VisualStyle.warm ? {
        warm: null
    } : value == VisualStyle.playful ? {
        playful: null
    } : value == VisualStyle.luxury ? {
        luxury: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SelectedFeature>): Array<_SelectedFeature> {
    return value.map((x)=>to_candid_SelectedFeature_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
