/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WizardInput {
    visualStyle: VisualStyle;
    siteType: SiteType;
    businessDescription: string;
    selectedFeatures: SelectedFeatures;
}
export type Timestamp = bigint;
export interface SiteSection {
    subheading: string;
    content: string;
    sectionType: SectionType;
    heading: string;
}
export interface VisualStyle {
    primaryColor: string;
    fontFamily: string;
    secondaryColor: string;
}
export interface SiteSummary {
    id: SiteId;
    status: PublishStatus;
    title: string;
    createdAt: Timestamp;
    subdomain?: string;
}
export interface LayoutMetadata {
    borderRadius: string;
    layoutStyle: string;
    fontFamily: string;
}
export type SiteId = bigint;
export type UserId = Principal;
export interface SitePublic {
    id: SiteId;
    status: PublishStatus;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    publishedUrl?: string;
    updatedAt: Timestamp;
    generatedData?: GeneratedSite;
    subdomain?: string;
}
export interface GeneratedSite {
    siteTitle: string;
    tagline: string;
    layout: LayoutMetadata;
    colorPalette: ColorPalette;
    sections: Array<SiteSection>;
}
export interface PreLaunchChecks {
    seo: boolean;
    formsValid: boolean;
    performanceHint: boolean;
    mobileReady: boolean;
}
export interface ColorPalette {
    accent: string;
    background: string;
    text: string;
    secondary: string;
    primary: string;
}
export interface SelectedFeatures {
    contactForm: boolean;
    bookings: boolean;
    auth: boolean;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum PublishStatus {
    published = "published",
    publishing = "publishing",
    unpublished = "unpublished",
    failed = "failed"
}
export enum SectionType {
    contact = "contact",
    about = "about",
    hero = "hero",
    services = "services",
    footer = "footer"
}
export enum SiteType {
    portfolio = "portfolio",
    blog = "blog",
    business = "business",
    landing = "landing",
    ecommerce = "ecommerce"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteSite(id: SiteId): Promise<void>;
    generateSite(input: WizardInput): Promise<SitePublic>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPreLaunchChecks(id: SiteId): Promise<PreLaunchChecks>;
    getSite(id: SiteId): Promise<SitePublic | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listMySites(): Promise<Array<SiteSummary>>;
    publishSite(id: SiteId): Promise<SitePublic>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSite(id: SiteId, title: string | null, generatedData: GeneratedSite | null): Promise<SitePublic>;
}
import type { ColorPalette as _ColorPalette, GeneratedSite as _GeneratedSite, LayoutMetadata as _LayoutMetadata, PublishStatus as _PublishStatus, SectionType as _SectionType, SelectedFeatures as _SelectedFeatures, SiteId as _SiteId, SitePublic as _SitePublic, SiteSection as _SiteSection, SiteSummary as _SiteSummary, SiteType as _SiteType, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, VisualStyle as _VisualStyle, WizardInput as _WizardInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteSite(arg0: SiteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async generateSite(arg0: WizardInput): Promise<SitePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.generateSite(to_candid_WizardInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateSite(to_candid_WizardInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreLaunchChecks(arg0: SiteId): Promise<PreLaunchChecks> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreLaunchChecks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreLaunchChecks(arg0);
            return result;
        }
    }
    async getSite(arg0: SiteId): Promise<SitePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSite(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSite(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMySites(): Promise<Array<SiteSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMySites();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMySites();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishSite(arg0: SiteId): Promise<SitePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.publishSite(arg0);
                return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishSite(arg0);
            return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateSite(arg0: SiteId, arg1: string | null, arg2: GeneratedSite | null): Promise<SitePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
                return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2));
            return from_candid_SitePublic_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GeneratedSite_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedSite): GeneratedSite {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PublishStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublishStatus): PublishStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SectionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionType): SectionType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SitePublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SitePublic): SitePublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SiteSection_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSection): SiteSection {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SiteSummary_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSummary): SiteSummary {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneratedSite]): GeneratedSite | null {
    return value.length === 0 ? null : from_candid_GeneratedSite_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SitePublic]): SitePublic | null {
    return value.length === 0 ? null : from_candid_SitePublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    tagline: string;
    layout: _LayoutMetadata;
    colorPalette: _ColorPalette;
    sections: Array<_SiteSection>;
}): {
    siteTitle: string;
    tagline: string;
    layout: LayoutMetadata;
    colorPalette: ColorPalette;
    sections: Array<SiteSection>;
} {
    return {
        siteTitle: value.siteTitle,
        tagline: value.tagline,
        layout: value.layout,
        colorPalette: value.colorPalette,
        sections: from_candid_vec_n15(_uploadFile, _downloadFile, value.sections)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subheading: string;
    content: string;
    sectionType: _SectionType;
    heading: string;
}): {
    subheading: string;
    content: string;
    sectionType: SectionType;
    heading: string;
} {
    return {
        subheading: value.subheading,
        content: value.content,
        sectionType: from_candid_SectionType_n18(_uploadFile, _downloadFile, value.sectionType),
        heading: value.heading
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SiteId;
    status: _PublishStatus;
    title: string;
    createdAt: _Timestamp;
    subdomain: [] | [string];
}): {
    id: SiteId;
    status: PublishStatus;
    title: string;
    createdAt: Timestamp;
    subdomain?: string;
} {
    return {
        id: value.id,
        status: from_candid_PublishStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        subdomain: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.subdomain))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SiteId;
    status: _PublishStatus;
    title: string;
    owner: _UserId;
    createdAt: _Timestamp;
    publishedUrl: [] | [string];
    updatedAt: _Timestamp;
    generatedData: [] | [_GeneratedSite];
    subdomain: [] | [string];
}): {
    id: SiteId;
    status: PublishStatus;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    publishedUrl?: string;
    updatedAt: Timestamp;
    generatedData?: GeneratedSite;
    subdomain?: string;
} {
    return {
        id: value.id,
        status: from_candid_PublishStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        publishedUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.publishedUrl)),
        updatedAt: value.updatedAt,
        generatedData: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.generatedData)),
        subdomain: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.subdomain))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    publishing: null;
} | {
    unpublished: null;
} | {
    failed: null;
}): PublishStatus {
    return "published" in value ? PublishStatus.published : "publishing" in value ? PublishStatus.publishing : "unpublished" in value ? PublishStatus.unpublished : "failed" in value ? PublishStatus.failed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: null;
} | {
    about: null;
} | {
    hero: null;
} | {
    services: null;
} | {
    footer: null;
}): SectionType {
    return "contact" in value ? SectionType.contact : "about" in value ? SectionType.about : "hero" in value ? SectionType.hero : "services" in value ? SectionType.services : "footer" in value ? SectionType.footer : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SiteSection>): Array<SiteSection> {
    return value.map((x)=>from_candid_SiteSection_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SiteSummary>): Array<SiteSummary> {
    return value.map((x)=>from_candid_SiteSummary_n25(_uploadFile, _downloadFile, x));
}
function to_candid_GeneratedSite_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GeneratedSite): _GeneratedSite {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SectionType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): _SectionType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SiteSection_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteSection): _SiteSection {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_SiteType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteType): _SiteType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WizardInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WizardInput): _WizardInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GeneratedSite | null): [] | [_GeneratedSite] {
    return value === null ? candid_none() : candid_some(to_candid_GeneratedSite_n29(_uploadFile, _downloadFile, value));
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    siteTitle: string;
    tagline: string;
    layout: LayoutMetadata;
    colorPalette: ColorPalette;
    sections: Array<SiteSection>;
}): {
    siteTitle: string;
    tagline: string;
    layout: _LayoutMetadata;
    colorPalette: _ColorPalette;
    sections: Array<_SiteSection>;
} {
    return {
        siteTitle: value.siteTitle,
        tagline: value.tagline,
        layout: value.layout,
        colorPalette: value.colorPalette,
        sections: to_candid_vec_n31(_uploadFile, _downloadFile, value.sections)
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subheading: string;
    content: string;
    sectionType: SectionType;
    heading: string;
}): {
    subheading: string;
    content: string;
    sectionType: _SectionType;
    heading: string;
} {
    return {
        subheading: value.subheading,
        content: value.content,
        sectionType: to_candid_SectionType_n34(_uploadFile, _downloadFile, value.sectionType),
        heading: value.heading
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visualStyle: VisualStyle;
    siteType: SiteType;
    businessDescription: string;
    selectedFeatures: SelectedFeatures;
}): {
    visualStyle: _VisualStyle;
    siteType: _SiteType;
    businessDescription: string;
    selectedFeatures: _SelectedFeatures;
} {
    return {
        visualStyle: value.visualStyle,
        siteType: to_candid_SiteType_n5(_uploadFile, _downloadFile, value.siteType),
        businessDescription: value.businessDescription,
        selectedFeatures: value.selectedFeatures
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): {
    contact: null;
} | {
    about: null;
} | {
    hero: null;
} | {
    services: null;
} | {
    footer: null;
} {
    return value == SectionType.contact ? {
        contact: null
    } : value == SectionType.about ? {
        about: null
    } : value == SectionType.hero ? {
        hero: null
    } : value == SectionType.services ? {
        services: null
    } : value == SectionType.footer ? {
        footer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteType): {
    portfolio: null;
} | {
    blog: null;
} | {
    business: null;
} | {
    landing: null;
} | {
    ecommerce: null;
} {
    return value == SiteType.portfolio ? {
        portfolio: null
    } : value == SiteType.blog ? {
        blog: null
    } : value == SiteType.business ? {
        business: null
    } : value == SiteType.landing ? {
        landing: null
    } : value == SiteType.ecommerce ? {
        ecommerce: null
    } : value;
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SiteSection>): Array<_SiteSection> {
    return value.map((x)=>to_candid_SiteSection_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
